# Generated by Django 4.2.4 on 2023-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="News Title")),
                (
                    "summery",
                    models.TextField(blank=True, verbose_name="Summery Of the News"),
                ),
                ("news_link", models.URLField(verbose_name="News Link")),
                (
                    "archive_link",
                    models.URLField(blank=True, verbose_name="Archive Link of News"),
                ),
                (
                    "is_draft",
                    models.BooleanField(default=True, verbose_name="Is this a draft?"),
                ),
            ],
        ),
    ]
