# Generated by Django 4.2.5 on 2023-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="About Page")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Categories of News"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Slug of this category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="News Title"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="News Author",
                    ),
                ),
                (
                    "summery",
                    models.TextField(blank=True, verbose_name="Summery Of the News"),
                ),
                ("news_link", models.URLField(verbose_name="News Link")),
                (
                    "archive_link",
                    models.URLField(blank=True, verbose_name="Archive Link of News"),
                ),
                ("published_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ManyToManyField(blank=True, to="news.category")),
            ],
        ),
    ]
