# Generated by Django 4.2.5 on 2023-10-24 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="Article",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-updated_at",)},
        ),
    ]
