# Generated by Django 4.2.4 on 2023-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Categories of News"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="news",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="This is a draft."),
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ManyToManyField(to="news.category"),
        ),
    ]
