# Generated by Django 4.2.4 on 2023-09-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_category_alter_news_is_draft_news_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="News Author"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ManyToManyField(blank=True, to="news.category"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="News Title"
            ),
        ),
    ]
