# Generated by Django 4.2.5 on 2023-09-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_news_published_at_news_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="This is a draft."),
        ),
    ]
