# Generated by Django 4.2.5 on 2023-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="About Page")),
            ],
        ),
        migrations.RemoveField(
            model_name="news",
            name="is_draft",
        ),
    ]
